education/graduation

.gitignore
README.md

- Adds application information to the READMe file.

Adds who can apply info

---

_data/mprice33/mprice33.md

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 
- [] **Tier 3** ✨: I want my project to be highlighted on stream.

Adding my profile(mprice33) to the yearbook

---

_data/caelinsutch/caelinsutch.md

JHS Represent

---

_data/harshendrashah/harshendrashah.md

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 
- [] **Tier 2** ✏️: I wrote a post on DEV about a project I built.
- [] **Tier 3** ✨: I want my project to be highlighted on stream.

Added harshedrashah

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Adds new date and time to submit PR
Updates on Tier 2 Swag

Updates May 23

---

_data/airada/airada.md

Added my github graduation info!

---

_data/PricopeStefan/PricopeStefan.md

Added details for graduation party

---

_data/twbrianho/twbrianho.md

Added myself (twbrianho).

---

_data/niklas2810/niklas2810.md

Add niklas2810

---

_data/Wout-M/Wout-M.md

Add Wout-M

---

_data/cairomo/cairomo.md

added information

---

_data/dudami43/dudami43.md

Pull Request: Class of 2020

---

_data/ccpandhare/ccpandhare.md

Add ccpandhare

---

_data/Pondorasti/Pondorasti.md

Add Alexandru Turcanu

---

_data/bdashore3/bdashore3.md

Includes my README and picture!
Signed-off-by: kingbri <bdashore3@gmail.com>

Add data for bdashore3 (Brian) with fixes indicated in PR #1421

---

_data/dsbuddy/dsbuddy.md

Added personal info

---

_data/shb9019/shb9019.md

Add shb9019

---

_data/bmedicke/bmedicke.md

Adds bmedicke

---

_data/basulaib/basulaib.md

Added basulaib

---

_data/hmartinez69/hmartinez69.md

Adding my data repo

---

_data/ayan59dutta/ayan59dutta.md
ayan59dutta/ayan59dutta.md

Adding profile information

---

_data/viaann/viaann.md

add viaann to yearbook 2020

---

_data/yashtandon019/yashtandon019.md

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 
- [ ✅] I have read the instructions on the README file before submitting my application. 
- [✅ ] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [ ✅] I have used the Markdown file template to add my information to the Year Book.
- [ ✅] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [ ✅] My application belongs to:
- [ ✅] **Tier 1** 📖: I added myself to the Year Book.
- [ ✅] I understand that a reviewer will merge my pull request after examining it or ask for …

info added

---

_data/bigyankarki/bigyankarki.md

Application for graduation

---

_data/shreyasbapat/shreyasbapat.md

Adding me to the yearbook

---

_data/halderjoydeep/halderjoydeep.md

Halderjoydeep patch 1

---

_data/dishpanda/dishpanda.md

add myself (dishpanda)

---

_data/Anureet19/Anureet19.md

anureet submission

---

_data/BourgonLaurent/BourgonLaurent.md

(BourgonLaurent) Application to the Class of 2020

---

_data/lopsandrea/lopsandrea.md

add lopsandrea

---

_data/GabriellBP/GabriellBP.md

Add GabriellBP

---

_data/KhaledMadkour/KhaledMadkour.md

This pull request template helps you complete an application to the **Class of 2020**. Use the checklist below to verify you have followed the instructions correctly. 
- [✅ ] I have read the instructions on the README file before submitting my application. 
- [✅ ] I made my submission by creating a folder on the `_data` folder and followed the naming convention mentioned in the instructions (`<username>`), added my profile picture and markdown file.
- [✅ ] I have used the Markdown file template to add my information to the Year Book.
- [✅ ] I have completed the form: `https://airtable.com/shrmuHxu38ZariKJi`
- [✅ ] My application belongs to:
- [✅ ] **Tier 1** 📖: I added myself to the Year Book.
- [✅ ] I understand that a reviewer will merge my pull request after examining it or ask for …

My graduation yearbook

---

_data/lrose07/lrose07.md

resubmitting info for lrose07

---

_data/lkbrough/lkbrough.md

adding my profile

---

_data/kashann/kashann.md

Adding my profile - kashann

---

_data/deppiedave64/deppiedave64.md

Add deppiedave64 to Year Book

---

_data/NotErikUden/NotErikUden.md

NotErikUden Graduation Request

---

_data/ashwinassysh/ashwinassysh.md

Changed the profile picture to square format

---

_data/rrifafauzikomara/rrifafauzikomara.md

Add my profile data (rrifafauzikomara)

---

.vscode/settings.json
_data/TravellerOnCode/TravellerOnCode.md

Traveller on code grad

---

_data/Anupam-dagar/Anupam-dagar.md

Add Anupam-dagar.

---

_data/AhmdNassar/AhmdNassar.md

change img size to be 1:1

---

_data/kirinrastogi/kirinrastogi.md

kirinrastogi apply to graduate

---

_data/HargovindArora/HargovindArora.md

In reference to PR #1805

---

_data/becnichelesmith/becnichelesmith.md

original pull: https://github.com/education/graduation/pull/173

---

_data/gaurav-chaurasia/gaurav-chaurasia.md

add image and md file

---

_data/josephkimsungha/josephkimsungha.md

josephkimsungha

---

README.md

added event updates to readme
